/**
 * Public gallery: finished examples anyone can browse and recreate with their own product or a short edit.
 * Only presentation data lives here (this package is public); the tested prompts behind every item ship
 * inside the API image (packages/api/content/gallery-recipes.json).
 */
import { CATALOG, priceFor } from "./index.js";

/** Business use, not subject: the subject lives in tags (recommendations are built from them). */
export type GalleryCategory = "product" | "motion" | "ugc" | "ads" | "lifestyle" | "social" | "posters" | "marketplace";

export interface GalleryItem {
  slug: string;
  title: string;
  category: GalleryCategory;
  /** Subject words first (plane, can, cat…), then format and mood; recommendations are built from them. */
  tags: string[];
  summary: string;
  media: { src: string; poster: string; kind: "video" | "image"; aspect: string };
  /** "required": a product photo drives the result; "optional": it may replace the hero object; "none": edit text only. */
  product: "required" | "optional" | "none";
  /** Spoken line for templates with a voice; the user may replace it. */
  script?: { default: string; maxWords: number };
  steps: { image?: string; tts?: string; video?: { model: string; duration: number; resolution?: string } };
  /** What to write in the edit box (marketplace cards take their text there). */
  editHint?: string;
  /** Cheap preview of the same idea: the video step on a draft model. */
  draft?: { model: string; resolution: string };
}

export const GALLERY_CATEGORIES: { id: GalleryCategory; label: string }[] = [
  { id: "product", label: "Product shots" }, { id: "motion", label: "Motion" }, { id: "ugc", label: "UGC" },
  { id: "ads", label: "Ads" }, { id: "lifestyle", label: "Lifestyle" }, { id: "social", label: "Memes & hooks" }, { id: "posters", label: "Posters" }, { id: "marketplace", label: "Marketplace" },
];

const V5 = { model: "seedance-2-fast", duration: 5 };
const DRAFT = { model: "seedance-2-mini", resolution: "480p" };

export const GALLERY: GalleryItem[] = [
  { slug: "ugc-selfie-review", title: "Selfie review", category: "ugc", tags: ["creator", "selfie", "review", "speech", "skincare", "bedroom", "ugc"],
    summary: "A creator holds your product to the camera and says your line, phone-selfie look.",
    media: { src: "/media/ugc-selfie-review.mp4", poster: "/media/ugc-selfie-review.jpg", kind: "video", aspect: "9:16" },
    product: "required", script: { default: "Okay, I really did not expect this to work. Three days in, and I'm hooked.", maxWords: 16 },
    steps: { image: "nano-banana-2", tts: "minimax-tts", video: V5 }, draft: DRAFT },
  { slug: "how-to-demo", title: "How-to demo", category: "ugc", tags: ["creator", "tutorial", "how-to", "speech", "beauty", "device", "bathroom", "ugc"],
    summary: "A creator explains and shows how to use your product, step by step, in one take.",
    media: { src: "/media/how-to-demo.mp4", poster: "/media/how-to-demo.jpg", kind: "video", aspect: "9:16" },
    product: "required", script: { default: "Here's how I use it. First this, then this, nice and easy. Two minutes, and I'm done.", maxWords: 30 },
    steps: { image: "nano-banana-2", tts: "minimax-tts", video: { model: "seedance-2-fast", duration: 10 } }, draft: DRAFT },
  { slug: "product-in-hand", title: "Product in hand", category: "ugc", tags: ["hands", "pov", "skincare", "cream", "texture", "bathroom", "ugc"],
    summary: "Point-of-view close-up: a hand shows your product and its texture.",
    media: { src: "/media/product-in-hand.mp4", poster: "/media/product-in-hand.jpg", kind: "video", aspect: "9:16" },
    product: "required", steps: { image: "nano-banana-2", video: V5 }, draft: DRAFT },
  { slug: "cat-knocks-it-off", title: "Cat knocks it off", category: "social", tags: ["cat", "pet", "meme", "funny", "kitchen", "drink", "can"],
    summary: "A cat stares at the camera and calmly pushes your product off the counter.",
    media: { src: "/media/cat-knocks-it-off-v2.mp4", poster: "/media/cat-knocks-it-off-v2.jpg", kind: "video", aspect: "9:16" },
    product: "required", steps: { image: "nano-banana-2", video: V5 }, draft: DRAFT },
  { slug: "dramatic-zoom", title: "Dramatic zoom", category: "social", tags: ["reaction", "face", "meme", "funny", "night", "laptop", "suspense"],
    summary: "A slow push-in to a face that just read something shocking. Hook for any reveal.",
    media: { src: "/media/dramatic-zoom.mp4", poster: "/media/dramatic-zoom.jpg", kind: "video", aspect: "9:16" },
    product: "none", steps: { image: "seedream-4.5", video: V5 }, draft: DRAFT },
  { slug: "splash-drop", title: "Splash drop", category: "motion", tags: ["water", "splash", "slow-motion", "drink", "can", "studio", "hook"],
    summary: "Your product drops into water in slow motion: a crown of splash in the first second.",
    media: { src: "/media/splash-drop.mp4", poster: "/media/splash-drop.jpg", kind: "video", aspect: "9:16" },
    product: "required", steps: { image: "nano-banana-2", video: V5 }, draft: DRAFT },
  { slug: "serum-shadows", title: "Palm shadows", category: "motion", tags: ["skincare", "bottle", "sunlight", "shadows", "beauty", "calm", "stone"],
    summary: "A slow push-in on your product while palm-leaf shadows sway in warm sun.",
    media: { src: "/media/serum-shadows.mp4", poster: "/media/serum-shadows.jpg", kind: "video", aspect: "3:4" },
    product: "required", steps: { image: "nano-banana-2", video: V5 }, draft: DRAFT },
  { slug: "lookbook-walk", title: "Lookbook walk", category: "lifestyle", tags: ["fashion", "coat", "street", "walking", "city", "film", "model"],
    summary: "A model walks toward the camera on a city street, editorial film look.",
    media: { src: "/media/lookbook-walk.mp4", poster: "/media/lookbook-walk.jpg", kind: "video", aspect: "3:4" },
    product: "optional", steps: { image: "seedream-4.5", video: V5 }, draft: DRAFT },
  { slug: "runner-feet", title: "Runner at sunrise", category: "lifestyle", tags: ["running", "shoes", "sneakers", "feet", "street", "sunrise", "sport"],
    summary: "Ankle-height tracking shot of a runner splashing through puddles at sunrise.",
    media: { src: "/media/runner-feet.mp4", poster: "/media/runner-feet.jpg", kind: "video", aspect: "9:16" },
    product: "optional", steps: { image: "seedream-4.5", video: V5 }, draft: DRAFT },
  { slug: "jet-climb", title: "Jet climb at golden hour", category: "lifestyle", tags: ["plane", "airliner", "aviation", "sky", "golden-hour", "travel", "cinematic"],
    summary: "An airliner climbs into the evening sky, long-lens aviation shot.",
    media: { src: "/media/jet-climb-v2.mp4", poster: "/media/jet-climb-v2.jpg", kind: "video", aspect: "16:9" },
    product: "none", steps: { image: "seedream-4.5", video: { model: "seedance-2-mini", duration: 5 } }, draft: DRAFT },
  { slug: "drone-sea-cliffs", title: "Drone over sea cliffs", category: "lifestyle", tags: ["drone", "aerial", "ocean", "cliffs", "sunrise", "travel", "landscape", "cinematic"],
    summary: "A low drone flight over turquoise waves toward green cliffs at sunrise.",
    media: { src: "/media/drone-sea-cliffs.mp4", poster: "/media/drone-sea-cliffs.jpg", kind: "video", aspect: "16:9" },
    product: "none", steps: { video: V5 }, draft: DRAFT },
  { slug: "night-car-rain", title: "Car in the rain at night", category: "lifestyle", tags: ["car", "automotive", "night", "rain", "neon", "city", "cinematic"],
    summary: "A sedan rolls through a wet neon street, tracking shot at wheel height.",
    media: { src: "/media/night-car-rain.mp4", poster: "/media/night-car-rain.jpg", kind: "video", aspect: "16:9" },
    product: "none", steps: { video: { model: "kling-3-std", duration: 5 } }, draft: DRAFT },
  { slug: "ingredient-macro-film", title: "Ingredient macro film", category: "motion", tags: ["macro", "ingredients", "coffee", "drink", "pour", "bubbles", "studio", "cinematic"],
    summary: "Ten seconds, five macro shots of your product's ingredients and texture, ending on the product itself.",
    media: { src: "/media/ingredient-macro-film.mp4", poster: "/media/ingredient-macro-film.jpg", kind: "video", aspect: "9:16" },
    product: "required", steps: { image: "nano-banana-2", video: { model: "seedance-2-fast", duration: 10 } }, draft: DRAFT },
  { slug: "ingredient-hover", title: "Balanced on its ingredient", category: "product", tags: ["ingredients", "ice", "pastel", "studio", "levitation", "skincare", "product"],
    summary: "Your product balances on its key ingredient over a block of ice, on a pastel backdrop from its packaging.",
    media: { src: "/media/ingredient-hover.jpg", poster: "/media/ingredient-hover.jpg", kind: "image", aspect: "4:5" },
    product: "required", steps: { image: "nano-banana-2" } },
  { slug: "cold-in-the-heat", title: "Cold in the heat", category: "lifestyle", tags: ["summer", "heat", "car", "sunset", "film", "drink", "coffee", "lifestyle"],
    summary: "A man in a hot car at sunset presses your ice-cold product to his neck. Warm film look.",
    media: { src: "/media/cold-in-the-heat.jpg", poster: "/media/cold-in-the-heat.jpg", kind: "image", aspect: "4:5" },
    product: "required", steps: { image: "nano-banana-2" } },
  // Stills (27.09.2026 photo set): one image step; product "optional" ones take the client's product in place of the hero object.
  { slug: "alps-lake", title: "Alpine lake at sunrise", category: "lifestyle", tags: ["lake", "mountains", "sunrise", "boat", "landscape", "travel", "nature"],
    summary: "A turquoise lake below snowy peaks, a rowing boat on the shore, morning mist.",
    media: { src: "/media/alps-lake.jpg", poster: "/media/alps-lake.jpg", kind: "image", aspect: "16:9" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "santorini", title: "Santorini stairway", category: "lifestyle", tags: ["santorini", "greece", "sea", "golden-hour", "architecture", "travel", "bougainvillea"],
    summary: "White houses and blue domes above the sea at golden hour.",
    media: { src: "/media/santorini.jpg", poster: "/media/santorini.jpg", kind: "image", aspect: "3:4" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "desert-dunes", title: "Caravan in the dunes", category: "lifestyle", tags: ["desert", "dunes", "camels", "dusk", "landscape", "travel", "cinematic"],
    summary: "Red dunes at dusk with a camel caravan on the ridge, long shadows.",
    media: { src: "/media/desert-dunes.jpg", poster: "/media/desert-dunes.jpg", kind: "image", aspect: "16:9" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "tokyo-night", title: "Tokyo alley in the rain", category: "lifestyle", tags: ["tokyo", "night", "rain", "neon", "lanterns", "street", "city", "cinematic"],
    summary: "A rainy alley with lanterns and neon reflections, someone with a clear umbrella.",
    media: { src: "/media/tokyo-night.jpg", poster: "/media/tokyo-night.jpg", kind: "image", aspect: "3:4" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "villa-pool", title: "Villa with an infinity pool", category: "lifestyle", tags: ["villa", "pool", "architecture", "real-estate", "sunset", "sea", "luxury"],
    summary: "A concrete villa and its infinity pool over the sea at sunset.",
    media: { src: "/media/villa-pool.jpg", poster: "/media/villa-pool.jpg", kind: "image", aspect: "16:9" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "kitchen-interior", title: "Minimal kitchen", category: "lifestyle", tags: ["kitchen", "interior", "real-estate", "oak", "minimal", "daylight", "home"],
    summary: "Oak cabinets, a stone island and pendant lights in bright daylight.",
    media: { src: "/media/kitchen-interior.jpg", poster: "/media/kitchen-interior.jpg", kind: "image", aspect: "4:3" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "latte-art", title: "Flat white and croissant", category: "lifestyle", tags: ["coffee", "croissant", "breakfast", "cafe", "top-down", "food", "morning"],
    summary: "A flat white with latte art and a croissant on a walnut table, morning light.",
    media: { src: "/media/latte-art.jpg", poster: "/media/latte-art.jpg", kind: "image", aspect: "4:5" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "sushi-board", title: "Omakase board", category: "lifestyle", tags: ["sushi", "japanese", "restaurant", "dark", "food", "macro"],
    summary: "Glistening nigiri on a dark wooden board, moody side light.",
    media: { src: "/media/sushi-board.jpg", poster: "/media/sushi-board.jpg", kind: "image", aspect: "16:9" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "pasta-table", title: "Family pasta dinner", category: "lifestyle", tags: ["pasta", "dinner", "italian", "family", "candid", "restaurant", "food", "warm"],
    summary: "A big bowl of spaghetti on a checkered cloth, hands reaching in, evening light.",
    media: { src: "/media/pasta-table.jpg", poster: "/media/pasta-table.jpg", kind: "image", aspect: "4:5" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "golden-retriever", title: "Retriever in autumn leaves", category: "lifestyle", tags: ["dog", "pet", "autumn", "park", "running", "golden-hour", "lifestyle"],
    summary: "A golden retriever running through autumn leaves, backlit by a low sun.",
    media: { src: "/media/golden-retriever.jpg", poster: "/media/golden-retriever.jpg", kind: "image", aspect: "4:5" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "founder-portrait", title: "Founder portrait", category: "lifestyle", tags: ["portrait", "founder", "office", "business", "startup", "smile", "team"],
    summary: "A founder in a navy sweater in a bright startup office, team blurred behind.",
    media: { src: "/media/founder-portrait.jpg", poster: "/media/founder-portrait.jpg", kind: "image", aspect: "4:5" },
    product: "none", steps: { image: "nano-banana-2" } },
  { slug: "boxing-gym", title: "Boxer wrapping hands", category: "lifestyle", tags: ["boxing", "gym", "sport", "portrait", "dramatic", "fitness"],
    summary: "A boxer wraps his hands in a gritty gym under hard top light.",
    media: { src: "/media/boxing-gym.jpg", poster: "/media/boxing-gym.jpg", kind: "image", aspect: "3:4" },
    product: "none", steps: { image: "seedream-4.5" } },
  { slug: "yoga-studio", title: "Yoga studio", category: "lifestyle", tags: ["yoga", "fitness", "studio", "calm", "plants", "wellness", "sport"],
    summary: "A yoga pose in a bright studio with big windows and plants.",
    media: { src: "/media/yoga-studio.jpg", poster: "/media/yoga-studio.jpg", kind: "image", aspect: "3:4" },
    product: "none", steps: { image: "nano-banana-2" } },
  { slug: "event-poster", title: "Jazz night poster", category: "posters", tags: ["poster", "music", "jazz", "event", "typography", "night"],
    summary: "A minimalist event poster with real typography. Change the headline and date in the edit.",
    media: { src: "/media/event-poster.jpg", poster: "/media/event-poster.jpg", kind: "image", aspect: "4:5" },
    product: "none", steps: { image: "nano-banana-pro" } },
  { slug: "cocktail-bar", title: "Cocktail at the bar", category: "product", tags: ["cocktail", "drink", "bar", "bokeh", "night", "food"],
    summary: "A drink on a marble bar with warm bokeh behind. Put your bottle or can in it.",
    media: { src: "/media/cocktail-bar.jpg", poster: "/media/cocktail-bar.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "seedream-4.5" } },
  { slug: "denim-editorial", title: "Denim editorial", category: "lifestyle", tags: ["fashion", "denim", "jacket", "editorial", "street", "sun", "model"],
    summary: "A street editorial in harsh midday sun. Put your garment on the model.",
    media: { src: "/media/denim-editorial.jpg", poster: "/media/denim-editorial.jpg", kind: "image", aspect: "3:4" },
    product: "optional", steps: { image: "nano-banana-2" } },
  { slug: "knit-studio", title: "Knitwear catalog", category: "lifestyle", tags: ["fashion", "knitwear", "sweater", "studio", "catalog", "calm", "model"],
    summary: "A calm catalog shot on a wooden stool. Put your garment on the model.",
    media: { src: "/media/knit-studio.jpg", poster: "/media/knit-studio.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "nano-banana-2" } },
  { slug: "sunglasses-beach", title: "Sunglasses at golden hour", category: "lifestyle", tags: ["sunglasses", "eyewear", "beach", "summer", "golden-hour", "fashion", "campaign"],
    summary: "A summer campaign close-up with wind and backlight. Put your frames on her.",
    media: { src: "/media/sunglasses-beach.jpg", poster: "/media/sunglasses-beach.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "nano-banana-2" } },
  { slug: "lipstick-macro", title: "Lipstick macro", category: "product", tags: ["lipstick", "beauty", "macro", "mirror", "dark", "product"],
    summary: "A beauty product on a mirror with a single rim light.",
    media: { src: "/media/lipstick-macro.jpg", poster: "/media/lipstick-macro.jpg", kind: "image", aspect: "1:1" },
    product: "optional", steps: { image: "seedream-4.5" } },
  { slug: "perfume-water", title: "Perfume in water", category: "product", tags: ["perfume", "fragrance", "water", "caustics", "summer", "beauty", "product"],
    summary: "A bottle half submerged in rippling water with sunlight caustics below.",
    media: { src: "/media/perfume-water.jpg", poster: "/media/perfume-water.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "seedream-4.5" } },
  { slug: "jewelry-hand", title: "Rings on linen", category: "product", tags: ["jewelry", "rings", "hand", "linen", "minimal", "beauty", "product"],
    summary: "Jewelry on a relaxed hand on white linen, soft diffused light.",
    media: { src: "/media/jewelry-hand.jpg", poster: "/media/jewelry-hand.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "seedream-4.5" } },
  { slug: "headphones-desk", title: "Headphones on the desk", category: "product", tags: ["headphones", "tech", "desk", "laptop", "lifestyle", "product", "afternoon"],
    summary: "A tech product on a wooden desk with a laptop and a mug, afternoon light.",
    media: { src: "/media/headphones-desk.jpg", poster: "/media/headphones-desk.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "seedream-4.5" } },
  { slug: "smartwatch-run", title: "Smartwatch on the run", category: "lifestyle", tags: ["smartwatch", "wearable", "running", "wrist", "tech", "sport", "product"],
    summary: "A runner's wrist with a watch, sweat drops, the park blurred behind.",
    media: { src: "/media/smartwatch-run.jpg", poster: "/media/smartwatch-run.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "seedream-4.5" } },
  { slug: "suv-mountain", title: "SUV above the clouds", category: "lifestyle", tags: ["car", "suv", "mountains", "clouds", "dawn", "automotive", "cinematic"],
    summary: "A car at a mountain viewpoint at dawn, clouds below. Put your car there.",
    media: { src: "/media/suv-mountain.jpg", poster: "/media/suv-mountain.jpg", kind: "image", aspect: "16:9" },
    product: "optional", steps: { image: "seedream-4.5" } },
  { slug: "sneaker-poster", title: "Sneaker launch poster", category: "posters", tags: ["poster", "sneakers", "shoes", "typography", "launch", "orange", "sport"],
    summary: "A bold drop poster with real typography. Put your shoe on it, change the words in the edit.",
    media: { src: "/media/sneaker-poster.jpg", poster: "/media/sneaker-poster.jpg", kind: "image", aspect: "4:5" },
    product: "optional", steps: { image: "nano-banana-pro" } },
  { slug: "ugc-selfie", title: "Selfie with a jar", category: "ugc", tags: ["selfie", "ugc", "skincare", "bathroom", "creator", "smile", "beauty"],
    summary: "A front-camera selfie holding a product next to the face, phone-camera look.",
    media: { src: "/media/ugc-selfie.jpg", poster: "/media/ugc-selfie.jpg", kind: "image", aspect: "9:16" },
    product: "optional", steps: { image: "nano-banana-2" } },
  // Batch 28.09.2026: marketplace cards, trendy stills and clips (people with the realism block).
  { slug: "palm-shadow-pedestal", title: "Palm shadows on stone", category: "product", tags: ["product", "still", "stone", "pedestal", "palm", "shadows", "sunlight", "premium", "drink", "can"],
    summary: "Your product on a travertine block in warm late-afternoon light, palm leaf shadows across the wall.",
    media: { src: "/media/palm-shadow-pedestal.jpg", poster: "/media/palm-shadow-pedestal.jpg", kind: "image", aspect: "1:1" },
    product: "required",
    editHint: "Anything to change, e.g. \"cooler morning light, a sprig of mint beside it\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-hero", title: "Listing hero with headline", category: "marketplace", tags: ["marketplace", "listing", "headline", "drink", "can", "bold", "typography"],
    summary: "The first image of a listing: your product on a bold colour with a big headline and one line under it.",
    media: { src: "/media/listing-hero.jpg", poster: "/media/listing-hero.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Headline and one short line, e.g. \"SPARKLING YUZU — zero sugar, real citrus\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-benefits", title: "Benefits with callouts", category: "marketplace", tags: ["marketplace", "listing", "infographic", "benefits", "skincare", "serum", "callouts"],
    summary: "Your product in the centre with three or four benefit callouts, thin lines and small icons: the classic second listing image.",
    media: { src: "/media/listing-benefits.jpg", poster: "/media/listing-benefits.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Three or four short benefits, e.g. \"brightens in 14 days; 15% vitamin C; for sensitive skin\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-ingredients", title: "Ingredients flat lay", category: "marketplace", tags: ["marketplace", "listing", "ingredients", "flat-lay", "natural", "soap", "top-down"],
    summary: "Top-down flat lay: your product among its raw ingredients, each one labelled.",
    media: { src: "/media/listing-ingredients.jpg", poster: "/media/listing-ingredients.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "The ingredients to label, e.g. \"olive oil, fig, shea butter\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-size", title: "Size guide", category: "marketplace", tags: ["marketplace", "listing", "size", "dimensions", "bag", "fashion", "technical"],
    summary: "Your product with clean dimension lines and measurements, so buyers know the size before they order.",
    media: { src: "/media/listing-size.jpg", poster: "/media/listing-size.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "The measurements, e.g. \"width 42 cm, height 38 cm, depth 12 cm\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-in-the-box", title: "What's in the box", category: "marketplace", tags: ["marketplace", "listing", "unboxing", "tech", "earbuds", "knolling", "contents"],
    summary: "Everything in the package laid out in a neat grid with labels: the product, cables, cases, papers.",
    media: { src: "/media/listing-in-the-box.jpg", poster: "/media/listing-in-the-box.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "What's in the package, e.g. \"earbuds, charging case, USB-C cable, ear tips\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-texture", title: "Texture swatch", category: "marketplace", tags: ["marketplace", "listing", "texture", "swatch", "skincare", "cream", "macro"],
    summary: "Your product next to a big macro swatch of its texture, with two short words about how it feels.",
    media: { src: "/media/listing-texture.jpg", poster: "/media/listing-texture.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Two or three words about the texture, e.g. \"lightweight, non-greasy\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-lineup", title: "Flavour line-up", category: "marketplace", tags: ["marketplace", "listing", "variants", "flavours", "drink", "can", "colourful"],
    summary: "Your product in three flavours or colours side by side, each with its name.",
    media: { src: "/media/listing-lineup.jpg", poster: "/media/listing-lineup.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "The variants, e.g. \"yuzu, blood orange, cucumber mint\"",
    steps: { image: "nano-banana-2" } },
  { slug: "listing-lifestyle", title: "In use, with a badge", category: "marketplace", tags: ["marketplace", "listing", "lifestyle", "coffee", "morning", "badge", "rating"],
    summary: "Your product in a real everyday moment with a bestseller badge and a star rating.",
    media: { src: "/media/listing-lifestyle.jpg", poster: "/media/listing-lifestyle.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Badge and rating text, e.g. \"Bestseller · 4.9 ★ from 2,300 reviews\"",
    steps: { image: "nano-banana-2" } },
  { slug: "flash-party", title: "Y2K flash party", category: "lifestyle", tags: ["party", "flash", "y2k", "friends", "night", "drink", "digicam", "trend"],
    summary: "Direct on-camera flash at a house party, digicam look: the Y2K aesthetic everyone is posting.",
    media: { src: "/media/flash-party.jpg", poster: "/media/flash-party.jpg", kind: "image", aspect: "4:5" },
    product: "optional",
    steps: { image: "nano-banana-2" } },
  { slug: "mirror-selfie", title: "Mirror selfie OOTD", category: "ugc", tags: ["selfie", "mirror", "outfit", "ootd", "fashion", "creator", "trend"],
    summary: "An outfit-of-the-day mirror selfie in an elevator, phone covering part of the face.",
    media: { src: "/media/mirror-selfie.jpg", poster: "/media/mirror-selfie.jpg", kind: "image", aspect: "9:16" },
    product: "optional",
    steps: { image: "nano-banana-2" } },
  { slug: "paparazzi-flash", title: "Paparazzi at night", category: "lifestyle", tags: ["fashion", "paparazzi", "flash", "night", "street", "celebrity", "trend", "bag"],
    summary: "A candid paparazzi-style flash shot of someone stepping out at night: the celebrity look for any brand.",
    media: { src: "/media/paparazzi-flash.jpg", poster: "/media/paparazzi-flash.jpg", kind: "image", aspect: "4:5" },
    product: "optional",
    steps: { image: "nano-banana-2" } },
  { slug: "shelfie", title: "Bathroom shelfie", category: "product", tags: ["skincare", "shelf", "bathroom", "shelfie", "aesthetic", "beauty", "trend"],
    summary: "A curated bathroom shelf with your product front and centre, soft morning light.",
    media: { src: "/media/shelfie.jpg", poster: "/media/shelfie.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    steps: { image: "nano-banana-2" } },
  { slug: "desk-setup", title: "Desk setup", category: "product", tags: ["desk", "setup", "tech", "earbuds", "workspace", "aesthetic", "night", "trend"],
    summary: "A clean evening desk setup with a monitor light bar and your tech product in the foreground.",
    media: { src: "/media/desk-setup.jpg", poster: "/media/desk-setup.jpg", kind: "image", aspect: "16:9" },
    product: "required",
    steps: { image: "nano-banana-2" } },
  { slug: "knolling-edc", title: "Everyday carry knolling", category: "product", tags: ["knolling", "top-down", "edc", "flat-lay", "tech", "organised", "trend"],
    summary: "Top-down knolling of everyday carry with your product as the hero.",
    media: { src: "/media/knolling-edc.jpg", poster: "/media/knolling-edc.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    steps: { image: "nano-banana-2" } },
  { slug: "iced-matcha", title: "Iced matcha to go", category: "lifestyle", tags: ["matcha", "cafe", "drink", "hand", "street", "summer", "film", "trend"],
    summary: "A hand holds an iced matcha latte in front of a cafe window, summer film look.",
    media: { src: "/media/iced-matcha.jpg", poster: "/media/iced-matcha.jpg", kind: "image", aspect: "4:5" },
    product: "optional",
    steps: { image: "nano-banana-2" } },
  { slug: "pilates-reformer", title: "Pilates reformer", category: "lifestyle", tags: ["pilates", "fitness", "wellness", "studio", "woman", "calm", "trend"],
    summary: "A candid moment on a pilates reformer in a bright studio.",
    media: { src: "/media/pilates-reformer.jpg", poster: "/media/pilates-reformer.jpg", kind: "image", aspect: "4:5" },
    product: "none",
    steps: { image: "nano-banana-2" } },
  { slug: "run-club", title: "Run club at dawn", category: "lifestyle", tags: ["running", "run-club", "friends", "city", "dawn", "sport", "trend"],
    summary: "A mixed run club crossing a bridge at dawn, candid and sweaty.",
    media: { src: "/media/run-club.jpg", poster: "/media/run-club.jpg", kind: "image", aspect: "16:9" },
    product: "none",
    steps: { image: "nano-banana-2" } },
  { slug: "gorpcore-trail", title: "Gorpcore trail", category: "lifestyle", tags: ["outdoor", "hiking", "gorpcore", "jacket", "mountains", "fashion", "trend"],
    summary: "A hiker in technical outdoor gear on a windy ridge: gorpcore fashion shot.",
    media: { src: "/media/gorpcore-trail.jpg", poster: "/media/gorpcore-trail.jpg", kind: "image", aspect: "4:5" },
    product: "optional",
    steps: { image: "nano-banana-2" } },
  { slug: "cafe-laptop", title: "Remote work cafe", category: "lifestyle", tags: ["remote-work", "laptop", "cafe", "freelance", "morning", "lifestyle", "saas"],
    summary: "Someone working on a laptop by a cafe window in the morning: the SaaS and freelance classic.",
    media: { src: "/media/cafe-laptop.jpg", poster: "/media/cafe-laptop.jpg", kind: "image", aspect: "16:9" },
    product: "none",
    steps: { image: "nano-banana-2" } },
  { slug: "clay-diorama", title: "Clay diorama", category: "lifestyle", tags: ["clay", "claymation", "3d", "playful", "diorama", "stop-motion", "trend"],
    summary: "Your product in a handmade clay miniature world: the playful stop-motion look.",
    media: { src: "/media/clay-diorama.jpg", poster: "/media/clay-diorama.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    steps: { image: "nano-banana-2" } },
  { slug: "chrome-y3k", title: "Chrome Y3K", category: "posters", tags: ["chrome", "y3k", "3d", "futuristic", "liquid-metal", "poster", "trend"],
    summary: "Your product floating among liquid-chrome shapes: the Y3K aesthetic.",
    media: { src: "/media/chrome-y3k.jpg", poster: "/media/chrome-y3k.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    steps: { image: "nano-banana-2" } },
  { slug: "dopamine-interior", title: "Dopamine decor", category: "lifestyle", tags: ["interior", "colourful", "home", "maximalist", "dopamine", "real-estate", "trend"],
    summary: "A bold, colourful maximalist living room: the dopamine decor trend.",
    media: { src: "/media/dopamine-interior.jpg", poster: "/media/dopamine-interior.jpg", kind: "image", aspect: "4:5" },
    product: "none",
    steps: { image: "nano-banana-2" } },
  { slug: "brutalist-sneaker", title: "Sneaker on concrete", category: "product", tags: ["sneakers", "shoes", "concrete", "brutalist", "hard-light", "street", "sport"],
    summary: "Your shoe on raw concrete steps in hard sunlight, sharp graphic shadows.",
    media: { src: "/media/brutalist-sneaker.jpg", poster: "/media/brutalist-sneaker.jpg", kind: "image", aspect: "4:5" },
    product: "optional",
    steps: { image: "nano-banana-2" } },
  { slug: "techno-poster", title: "Techno night poster", category: "posters", tags: ["poster", "techno", "music", "event", "swiss", "typography", "night"],
    summary: "A Swiss-grid techno event poster with real typography. Change the words in the edit.",
    media: { src: "/media/techno-poster.jpg", poster: "/media/techno-poster.jpg", kind: "image", aspect: "4:5" },
    product: "none",
    editHint: "The poster text, e.g. \"NIGHT SHIFT · Warehouse 9 · Sat 18.10 · 23:00–07:00\"",
    steps: { image: "nano-banana-2" } },
  { slug: "cafe-menu-poster", title: "Cafe menu poster", category: "posters", tags: ["poster", "menu", "cafe", "coffee", "typography", "food", "small-business"],
    summary: "A clean specialty-coffee menu board with prices. Put your menu in the edit.",
    media: { src: "/media/cafe-menu-poster.jpg", poster: "/media/cafe-menu-poster.jpg", kind: "image", aspect: "4:5" },
    product: "none",
    editHint: "Menu items with prices, e.g. \"Flat white 3.5; Iced matcha 4.5; Cortado 3\"",
    steps: { image: "nano-banana-2" } },
  { slug: "app-in-hand", title: "App in hand", category: "lifestyle", tags: ["app", "phone", "saas", "mockup", "hand", "street", "tech"],
    summary: "A real hand holds a phone with your app on screen, outdoors. Upload a screenshot as the product.",
    media: { src: "/media/app-in-hand.jpg", poster: "/media/app-in-hand.jpg", kind: "image", aspect: "4:5" },
    product: "optional",
    steps: { image: "nano-banana-2" } },
  { slug: "grwm", title: "Get ready with me", category: "ugc", tags: ["grwm", "creator", "skincare", "mirror", "speech", "morning", "ugc", "trend"],
    summary: "Get-ready-with-me: a creator applies your product at the mirror and talks to the camera.",
    media: { src: "/media/grwm.mp4", poster: "/media/grwm.jpg", kind: "video", aspect: "9:16" },
    product: "required",
    script: { default: "Okay, step one, always this serum first. Two drops, pat it in, done.", maxWords: 16 },
    steps: { image: "nano-banana-2", tts: "minimax-tts", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  { slug: "unboxing-asmr", title: "Unboxing ASMR", category: "ugc", tags: ["unboxing", "asmr", "hands", "tech", "earbuds", "top-down", "trend"],
    summary: "Top-down hands slowly open a box and lift out your product, crisp ASMR sounds.",
    media: { src: "/media/unboxing-asmr.mp4", poster: "/media/unboxing-asmr.jpg", kind: "video", aspect: "9:16" },
    product: "required",
    steps: { image: "nano-banana-2", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  { slug: "street-interview", title: "Street interview", category: "social", tags: ["interview", "street", "microphone", "speech", "city", "social", "trend"],
    summary: "A passer-by answers a question into a handheld mic on a busy street. Write their answer.",
    media: { src: "/media/street-interview.mp4", poster: "/media/street-interview.jpg", kind: "video", aspect: "9:16" },
    product: "none",
    script: { default: "Honestly? I switched last month and I'm never going back.", maxWords: 14 },
    steps: { image: "nano-banana-2", tts: "minimax-tts", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  { slug: "cheese-pull", title: "Cheese pull", category: "motion", tags: ["food", "burger", "cheese", "slow-motion", "restaurant", "macro", "appetite"],
    summary: "Slow-motion cheese pull from a smash burger: the food hook that never gets old.",
    media: { src: "/media/cheese-pull.mp4", poster: "/media/cheese-pull.jpg", kind: "video", aspect: "9:16" },
    product: "none",
    steps: { image: "nano-banana-2", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  { slug: "matcha-pour", title: "Matcha pour", category: "motion", tags: ["matcha", "drink", "pour", "macro", "slow-motion", "cafe", "trend"],
    summary: "Bright green matcha poured over ice and milk in slow motion.",
    media: { src: "/media/matcha-pour.mp4", poster: "/media/matcha-pour.jpg", kind: "video", aspect: "9:16" },
    product: "none",
    steps: { image: "nano-banana-2", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  { slug: "claymation-hop", title: "Clay world", category: "social", tags: ["clay", "claymation", "stop-motion", "playful", "3d", "can", "trend"],
    summary: "Your product moves through a tiny handmade clay world while the clay sun winks.",
    media: { src: "/media/claymation-hop.mp4", poster: "/media/claymation-hop.jpg", kind: "video", aspect: "9:16" },
    product: "required",
    steps: { image: "nano-banana-2", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  { slug: "night-drive-pov", title: "Night drive POV", category: "lifestyle", tags: ["car", "driving", "night", "city", "pov", "neon", "cinematic"],
    summary: "Driver's point of view through a city at night, hands on the wheel, lights streaking by.",
    media: { src: "/media/night-drive-pov.mp4", poster: "/media/night-drive-pov.jpg", kind: "video", aspect: "9:16" },
    product: "none",
    steps: { image: "nano-banana-2", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  { slug: "outfit-snap", title: "Outfit change snap", category: "social", tags: ["outfit", "transition", "fashion", "snap", "creator", "trend", "mirror"],
    summary: "The viral outfit transition: a snap of the fingers and the look changes.",
    media: { src: "/media/outfit-snap.mp4", poster: "/media/outfit-snap.jpg", kind: "video", aspect: "9:16" },
    product: "optional",
    steps: { image: "nano-banana-2", video: { model: "seedance-2-fast", duration: 5 } }, draft: DRAFT },
  // Batch 28.09.2026: marketplace cards, trendy stills and clips (people with the realism block).
  { slug: "ad-burst", title: "Burst ad", category: "ads", tags: ["ad", "banner", "social", "drink", "can", "bold", "stickers", "cta"],
    summary: "Your product on a loud colour with a starburst, two sticker badges and a button: a scroll-stopping feed ad.",
    media: { src: "/media/ad-burst.jpg", poster: "/media/ad-burst.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Headline, two stickers and a button, e.g. \"YUZU POP; zero sugar; real fruit; Try it\"",
    steps: { image: "nano-banana-2" } },
  { slug: "ad-story-swipe", title: "Story ad with swipe-up", category: "ads", tags: ["ad", "stories", "vertical", "skincare", "serum", "cta", "gradient"],
    summary: "A full-screen stories ad: product hero, headline, one line and a shop button placed clear of the app UI.",
    media: { src: "/media/ad-story-swipe.jpg", poster: "/media/ad-story-swipe.jpg", kind: "image", aspect: "9:16" },
    product: "required",
    editHint: "Headline, one line and a button, e.g. \"GLOW IN 14 DAYS; vitamin C 15%; Shop now\"",
    steps: { image: "nano-banana-2" } },
  { slug: "ad-discount", title: "Discount with promo code", category: "ads", tags: ["ad", "sale", "discount", "promo-code", "summer", "skincare", "banner"],
    summary: "A sale ad: giant discount numbers, your product, a promo-code chip and a deadline line.",
    media: { src: "/media/ad-discount.jpg", poster: "/media/ad-discount.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Discount, code and deadline, e.g. \"-30%; code SUN30; this week only\"",
    steps: { image: "nano-banana-2" } },
  { slug: "ad-testimonial", title: "Review ad", category: "ads", tags: ["ad", "review", "testimonial", "stars", "social-proof", "soap", "quote"],
    summary: "Social proof as an ad: a five-star customer quote on a card next to your product.",
    media: { src: "/media/ad-testimonial.jpg", poster: "/media/ad-testimonial.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "The quote, the name and the stars, e.g. \"My hands have never smelled this good — Anna, Berlin, 5 stars\"",
    steps: { image: "nano-banana-2" } },
  { slug: "ad-launch", title: "New launch", category: "ads", tags: ["ad", "launch", "new", "tech", "earbuds", "reveal", "gradient"],
    summary: "Announce something new: a NEW sticker, your product floating in light rays and a launch date.",
    media: { src: "/media/ad-launch.jpg", poster: "/media/ad-launch.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Headline and launch date, e.g. \"Meet NOVA; out 10.10\"",
    steps: { image: "nano-banana-2" } },
  { slug: "ad-bundle", title: "Bundle offer", category: "ads", tags: ["ad", "bundle", "offer", "3-for-2", "coffee", "drink", "price"],
    summary: "Three of your product with a ribbon offer like 3-for-2: the classic basket-builder ad.",
    media: { src: "/media/ad-bundle.jpg", poster: "/media/ad-bundle.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "The offer and one line, e.g. \"3 for 2; stock up for the week\"",
    steps: { image: "nano-banana-2" } },
  { slug: "ad-before-after", title: "Problem and solution", category: "ads", tags: ["ad", "before-after", "problem", "solution", "split", "bag", "eco"],
    summary: "A split ad: the problem on the left in grey, your product as the answer on the right in colour.",
    media: { src: "/media/ad-before-after.jpg", poster: "/media/ad-before-after.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "A short line for each side, e.g. \"12 plastic bags a week | one tote for all of it\"",
    steps: { image: "nano-banana-2" } },
  { slug: "ad-price-drop", title: "Price tag drop", category: "ads", tags: ["ad", "price", "drop", "sneakers", "shoes", "street", "cta"],
    summary: "Your product in a real setting with a bold price sticker, one line and a shop button: a drop announcement.",
    media: { src: "/media/ad-price-drop.jpg", poster: "/media/ad-price-drop.jpg", kind: "image", aspect: "4:5" },
    product: "required",
    editHint: "Price, one line and a button, e.g. \"€89; trail-ready, city-proof; Shop the drop\"",
    steps: { image: "nano-banana-2" } },
];

export const galleryItem = (slug: string): GalleryItem | undefined => GALLERY.find((g) => g.slug === slug);

/** Credits for one recreate: image + voice + video (or the draft video). The voice is priced by its length. */
export function galleryPrice(item: GalleryItem, opts: { draft?: boolean; scriptChars?: number } = {}): number {
  const m = (id: string) => { const x = CATALOG.find((c) => c.id === id); if (!x) throw new Error(`gallery ${item.slug}: unknown model ${id}`); return x; };
  let credits = 0;
  if (item.steps.image) credits += priceFor(m(item.steps.image), { n: 1 }).credits;
  if (item.steps.tts) credits += priceFor(m(item.steps.tts), { text: "x".repeat(opts.scriptChars ?? item.script?.default.length ?? 100) }).credits;
  const v = item.steps.video;
  if (v) {
    const model = opts.draft && item.draft ? item.draft.model : v.model;
    const resolution = opts.draft && item.draft ? item.draft.resolution : v.resolution;
    credits += priceFor(m(model), { duration: v.duration, resolution }).credits;
  }
  return credits;
}

/**
 * "More like this": items sharing the most tags (subject words weigh the same as format words), same category
 * as a tie-breaker, then the rest in gallery order so the row is never empty.
 */
export function relatedGallery(slug: string, n = 8): GalleryItem[] {
  const me = galleryItem(slug);
  if (!me) return GALLERY.slice(0, n);
  const mine = new Set(me.tags);
  const scored = GALLERY.filter((g) => g.slug !== slug).map((g, i) => ({ g, i, s: g.tags.filter((t) => mine.has(t)).length * 2 + (g.category === me.category ? 3 : 0) }));
  return scored.sort((a, b) => b.s - a.s || a.i - b.i).slice(0, n).map((x) => x.g);
}
